language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
    - DJANGO='Django>=1.4,<1.5'
    - DJANGO='Django>=1.5,<1.6'
    - DJANGO='Django>=1.6,<1.7'
    - DJANGO='Django>=1.7,<1.8'
install:
  - travis_retry pip install $DJANGO
# command to run tests
script: python manage.py test absolute
